apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-yayj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-yayj
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-yayj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-yayj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-yayj
    spec:
      containers:
      - image: quay.io/rsoaresd_org/release-e2e-deploy-tenant/appstudio/dc-metro-map-yayj@sha256:2c590330b3680694ad73658227f5254d867786829a9884a73047de2990a84578
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
